export enum ERoutes {
  LOGIN = "/auth/login",
  AUTH_ERROR = "/auth/error",
  REGISTER = "/auth/register",
  PUBLIC_ROOT = "/",
  AUTH_PREFIX = "/api/auth",
  SETTINGS = "/settings",
  AUTH_NEW_VERIFICATION = "/auth/new-verification",
  RESET_PASSWORD = "/auth/reset-password",
  AUTH_NEW_PASSWORD = "/auth/new-password",
  ACCOUNT = "/account",
  API_DEMO = "/apiDemo/pokemon/cards?q=&page=1&pageSize=24",
  POKEMON_CARD ="/apiDemo/card",
  ADMIN = "/admin",
}
